### ISSUE TITLE
Replace Bagdes by Tags in Card props

### ISSUE THREAD

**Issue by pprev94** [codegouvfr/react-dsfr#164]
In the documentation of dsfr (https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/carte) it's already tags instead of badges.
So we should apply changes to Card component

I can work on a PR

**Comment by ocruze** [comment]
Sorry we read a little too fast. So it seems that both tags and badges are possible but not at the same time. We would like to have the possibility to choose from tags or badges.

We thought of something like this: changing the following prop `badges`: BadgeProps[] | TagProps[] 
Maybe reuse the <Badge /> and <Tag /> components?

**Comment by enguerranws** [comment]
@ocruze Seems fine

**Comment by garronej** [comment]
Hi @slafayIGN, thank you for bringing those rules to my attention.

If I understand correctly, you're saying that the current Card component allows usages that don't adhere to the official DSFR guidelines. Is that correct?
Are you suggesting that we should strengthen the Props type definition so that TypeScript will throw an error if all the rules aren't followed?

Should the component be completely overhauled?
Would anyone be willing to take this on? It seems straightforward, as there's no logic involved.

**Comment by garronej** [comment]
@ihiverlet, that's correct!
Thank you for bringing this to my attention.
I'm currently in the midst of a complete overhaul of our release pipeline, so I can't easily make a release at the moment. However, I'll address this issue as soon as I've finished with the ops work!
