### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by arnaudambro** [codegouvfr/react-dsfr#292]
Hello

I'm building a Remix app here: 
https://github.com/betagouv/zacharie/commit/bafd08b94a6056c58e0b2d248bc84fc8c1b87f4e#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890dd

if you try and run this commit, you should get this error

```
export { default } from "./Header";
^^^^^^

SyntaxError: Unexpected token 'export'
```

the way I fixed it is to add those lines to the vite config
https://github.com/betagouv/zacharie/commit/c6174f0cbc406cf1ed700b9c4750aa41379ae40b

```
  ssr: {
     noExternal: ["@codegouvfr/react-dsfr"],
   },
```

am I doing things right ?

**Comment by arnaudambro** [comment]
mmm I don't know if this is related, but I need to 

`import "@codegouvfr/react-dsfr/main.css";`

if not, in production, I miss this css file

**Comment by garronej** [comment]
Hello @arnaudambro,  

Yes you are doing things right with `ssr.noExternal`, node runs in CommonJS mode by default and react-dsfr components are shipped in ESM so Vite needs to transpile them.  

Regarding how you import the global CSS.  
Yes, you should use the `import "@codegouvfr/react-dsfr/main.css""` statement you can remove [this](https://github.com/betagouv/zacharie/blob/064c421933b764300ba69aa85e14a9f64512959e/app/root.tsx#L66).  

Some gotcha to be aware of since I do not provide an integration for Remix:  

You can't use thoses hooks:  

```tsx
import { useIsDark } from "@codegouvfr/react-dsfr/useIsDark";
import { useColors } from "@codegouvfr/react-dsfr/useColors";
```  

It should not be a big deal since the colors are accessible as CSS variables in the fr object:  

```ts
import { fr } from "@codegouvfr/react-dsfr";

fr.colors.xxx
```

See [colors picker tool](https://components.react-dsfr.codegouv.studio/?path=/docs/%F0%9F%8E%A8-color-helper--page).  

Consequently you won't be alble to use the MUI integration either:  
https://react-dsfr.codegouv.studio/mui  

If it's a prolem for you I can work on a SSR provider for Remix.  
I didn't bother since all the teams that I know of works with either Next Vite or Create React App.  

Best

**Comment by arnaudambro** [comment]
thanks @garronej 

what I actually did on top of the vite config is

```
root.tsx


import dsfrCss from "@codegouvfr/react-dsfr/main.css?url";


export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <head>
        <meta charSet="utf-8" />
        <link rel="stylesheet" href={dsfrCss} />
        <Links />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}
```

and everything works fine
