### ISSUE TITLE
How to use custom favicon in next-appdir

### ISSUE THREAD

**Issue by powderham** [codegouvfr/react-dsfr#60]
I'm currently looking at implementing dsfr on my app.

Upon following the docs, since including `DsfrHead` I've had my favicons replaced by the dsfr favicon. 

Looking at the source code below, I don't see a way to overwrite this.  

```
export function DsfrHead(props) {
    const { defaultColorScheme, preloadFonts = [] } = props;
    return (React.createElement(React.Fragment, null,
        ...
        React.createElement("link", { rel: "icon", href: getAssetUrl(FaviconSvg), type: "image/svg+xml" }),
        React.createElement("link", { rel: "shortcut icon", href: getAssetUrl(FaviconIco), type: "image/x-icon" }),
        ));
}
```

Is this intentional, or can I open a PR to pass a prop to toggle these favicons on/off?

**Comment by garronej** [comment]
Hi @powderham,  

It's intentional since all governemental website should have the same favicon but allright, it could be a good idea to at least give an option not to include the favicon.  

That being said, are you freelancing for the french public service?  
I'm saying that because this design system is only meant to be used for French Governemental website...

**Comment by garronej** [comment]
I mean do whant, it's open source and I'm just the dev but be aware that you could get your website taken down by the french authorities if it looks too much alike a governemental website...

**Comment by powderham** [comment]
Interesting, I can't see this written anywhere in the guides. Perhaps best to do so, given it's in the public domain.

I'm not freelancing for the french public service, but I think the component library is smart, and with a few tweaks would serve as a nice base for my web app.

**Comment by garronej** [comment]
Hi, I found the GGU of the DS: https://www.systeme-de-design.gouv.fr/cgu/

**Comment by rtaieb** [comment]
Hi @garronej ,
Could this issue be reopened ?
It would be nice to be able to opt out of the DSFR favicon when using NextJS app dir.
(As @powderham , I could'n find a way to do it).

Thanks :)

**Comment by garronej** [comment]
Hi @rtaieb,  
The issue here is that the Marianne Favicon is a requirement from the DSFR team it's not something that you are supposed to customize.    
I guess we could argue that you might want to programatically edit the favicon to show notifications for example.  
Could you explain your usecase just so I can motivate why I'm enabling the favicon to be customized.   

Thanks

**Comment by rtaieb** [comment]
Well I'm working for the [ADEME](https://www.ademe.fr/), which is associated to the Ministère de la Transition Ecologique.
From what we've been told by the ADEME lead desinger, the ADEME can take the DSFR as a basis, and then tweak it depending on the product / design needs.
That's what I've been doing so far, but couldn't override the favicon set by DsfrHead component...

**Comment by garronej** [comment]
Ok, I'll add an option

**Comment by garronej** [comment]
Done.  
It's beeing released.  
It's ... v1.0.0

**Comment by rtaieb** [comment]
Thank you so much for this, and in fact for this whole module 🥇

**Comment by garronej** [comment]
You're welcome ☺️
